import './globals.css';

import type { Metadata } from 'next';
import { Geist } from 'next/font/google';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body className={`${geistSans.className} bg-gray-50 text-gray-900 antialiased`}>
                {children}
            </body>
        </html>
    );
}
